use_frameworks!
platform :ios, '12.0'

target 'KenticoKontentDelivery_Example' do
  pod 'KenticoKontentDelivery', :path => '../'
  pod 'AlamofireImage', '~> 3.4.1'
  pod 'ObjectMapper', '~> 3.4.1'

  target 'KenticoKontentDelivery_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'ObjectMapper', '~> 3.4.1'
  end
end
