use_frameworks!
platform :ios, '10.0'

target 'KenticoCloud_Example' do
  pod 'KenticoCloud', :path => '../'
  pod 'AlamofireImage', '~> 3.1'

  target 'KenticoCloud_Tests' do
    inherit! :search_paths
    pod 'KenticoCloud', :path => '../'
    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
    
  end
end

