use_frameworks!
platform :ios, '11.0'

target 'KenticoKontentDelivery_Example' do
  pod 'KenticoKontentDelivery', :path => '../'
  pod 'AlamofireImage', '~> 3.6.0'


  target 'KenticoKontentDelivery_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
